spring.application.name=DBP_proyecto

cloudinary.cloud-name=TU_CLOUD_NAME
cloudinary.api-key=TU_API_KEY
cloudinary.api-secret=TU_API_SECRET

google.places.api-key=${GOOGLE_PLACES_API_KEY}
google.places.base-url=https://places.googleapis.com/v1
google.places.timeout-ms=5000
