spring.application.name=DBP_proyecto

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Google Places API
google.places.api-key=${GOOGLE_PLACES_API_KEY}
google.places.base-url=https://places.googleapis.com/v1
google.places.timeout-ms=5000

# Base de Datos H2
spring.datasource.url=jdbc:h2:mem:dbp_proyecto;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2
# URL: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
# create-drop: borra y recrea las tablas en cada arranque (ideal para desarrollo)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

